@extends("admin.layouts/".config("settings.admin"))

@section("content")
    <div>Aahgshgashhsahsghasgh</div>
    <div>Aahgshgashhsahsghasgh</div>
    <div>Aahgshgashhsahsghasgh</div>
    <div>Aahgshgashhsahsghasgh</div>
    <div>Aahgshgashhsahsghasgh</div>
    <div>Aahgshgashhsahsghasgh</div>
    <div>Aahgshgashhsahsghasgh</div>
    <div>Aahgshgashhsahsghasgh</div>
    <div>Aahgshgashhsahsghasgh</div>
    <div>Aahgshgashhsahsghasgh</div>
    <div>Aahgshgashhsahsghasgh</div>
    <div>Aahgshgashhsahsghasgh</div>
    <div>Aahgshgashhsahsghasgh</div>
    <div>Aahgshgashhsahsghasgh</div>
    <div>Aahgshgashhsahsghasgh</div>
    <div>Aahgshgashhsahsghasgh</div>
    <div>Aahgshgashhsahsghasgh</div>
    <div>Aahgshgashhsahsghasgh</div>
    <div>Aahgshgashhsahsghasgh</div>
    <div>Aahgshgashhsahsghasgh</div>
    <div>Aahgshgashhsahsghasgh</div>
    <div>Aahgshgashhsahsghasgh</div>
    <div>Aahgshgashhsahsghasgh</div>
@endsection
